### ISSUE TITLE
Emulator view improvement: button alignment, background image

### ISSUE THREAD

**Issue by vaspa** [ossw/ossw-android#20]
Landscape mode is not very good looking. This page can be fixed in portrait orientation, maybe.
Some background as the following one can be useful.
![image](https://cloud.githubusercontent.com/assets/14954105/11562035/982099f2-99cb-11e5-8cff-c1564dea7844.png)

**Comment by althink** [comment]
I've merged your changes. I like the new buttons and settings screen is now much faster. But the background in watchset preview is a little bit too much for me :D So I've removed it and hide watchset name in landscape mode so now you don't have to scroll the screen and it looks good (at least for me ;) ). I don't want to lock watchset preview to portrait mode because if for someone it's really unusable then he can force portrait mode by himself and we don't force others to do that.
